### ISSUE TITLE
AttributeError: 'FlagEmbeddingReranker' object has no attribute '__pydantic_private__'. 

### ISSUE THREAD

**Issue by ginnyyk** [GAIR-NLP/OpenResearcher#5]
I was attempting to execute the code. When I followed the instruction to run the RAG application on "ui_app.py", I've got error 

```
File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
File "/OpenResearcher/ui_app.py", line 6, in <module>
    from init import hybrid_retriever
  File "/OpenResearcher/init.py", line 14, in <module>
    flag_embedding_reranker = FlagEmbeddingReranker(model=rerank_model_path, top_n=10)
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/llama_index/postprocessor/flag_embedding_reranker/base.py", line 30, in __init__
    self._model = FlagReranker(
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/pydantic/main.py", line 837, in __setattr__
    if self.__pydantic_private__ is None or name not in self.__private_attributes__:
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/pydantic/main.py", line 825, in __getattr__
    return super().__getattribute__(item)  # Raises AttributeError if appropriate
AttributeError: 'FlagEmbeddingReranker' object has no attribute '__pydantic_private__'. Did you mean: '__pydantic_complete__'?
```

The version of pydantic=2.8.2

When I tried to downloaded pydantic to 1.1 to avoid the error, I've got another error
```
 File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 600, in _run_script
    exec(code, module.__dict__)
  File "/OpenResearcher/ui_app.py", line 4, in <module>
    from service.query_understanding import Multi_Turn_Query_Understanding
  File "/OpenResearcher/service/query_understanding.py", line 1, in <module>
    from llm.chat_llm import chat
  File "/OpenResearcher/llm/chat_llm.py", line 1, in <module>
    from openai import OpenAI
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/__init__.py", line 8, in <module>
    from . import types
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/types/__init__.py", line 5, in <module>
    from .batch import Batch as Batch
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/types/batch.py", line 7, in <module>
    from .._models import BaseModel
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/_models.py", line 36, in <module>
    from ._utils import (
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/_utils/__init__.py", line 3, in <module>
    from ._utils import (
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/_utils/_utils.py", line 24, in <module>
    from .._compat import parse_date as parse_date, parse_datetime as parse_datetime
  File "/miniconda3/envs/openresearcher/lib/python3.10/site-packages/openai/_compat.py", line 20, in <module>
PYDANTIC_V2 = pydantic.VERSION.startswith("2.")
AttributeError: 'StrictVersion' object has no attribute 'startswith'
```

**Comment by Zeetc** [comment]
Perhaps the flag-embedding library for llama-index has been updated. Can you try using “llama-index-postprocessor-flag-embedding-reranker==0.12.2” and ”pydantic==2.6.4“?  Thanks!

**Comment by ginnyyk** [comment]
Can I have the version of different libraries since the changes causes the incompatible off the others libraries, such as llama-index-core, llama-index-llms-openai, llama-index-embeddings-huggingface, etc.?
I'm not sure which version I should use. Thank you.

**Comment by Zeetc** [comment]
There is a compatible version, but as it is an environment used during the development process, there may be many unnecessary libraries. You can choose the corresponding version according to your needs. Thanks!
Package                                           Version
------------------------------------------------- ---------------
accelerate                                        0.28.0
aiohttp                                           3.9.5
aiosignal                                         1.3.1
aiosqlite                                         0.20.0
albumentations                                    1.4.2
altair                                            5.2.0
annotated-types                                   0.6.0
anyio                                             4.3.0
appdirs                                           1.4.4
asgiref                                           3.8.1
asttokens                                         2.4.1
async-timeout                                     4.0.3
attrs                                             23.2.0
Authlib                                           1.3.1
backoff                                           2.2.1
bcrypt                                            4.1.2
beautifulsoup4                                    4.12.3
bentoml                                           1.3.1
blinker                                           1.7.0
blis                                              0.7.11
boto3                                             1.34.150
botocore                                          1.34.150
bs4                                               0.0.2
build                                             1.1.1
cachetools                                        5.3.3
camelot-py                                        0.11.0
catalogue                                         2.0.10
cattrs                                            23.1.2
certifi                                           2024.2.2
cffi                                              1.16.0
chardet                                           5.2.0
charset-normalizer                                3.3.2
chroma-hnswlib                                    0.7.3
chromadb                                          0.4.24
circus                                            0.18.0
click                                             8.1.7
click-option-group                                0.5.6
cloudpathlib                                      0.16.0
cloudpickle                                       3.0.0
cohere                                            5.6.2
coloredlogs                                       15.0.1
comm                                              0.2.2
confection                                        0.1.4
cryptography                                      42.0.5
cupy-cuda12x                                      12.1.0
cymem                                             2.0.8
dataclasses-json                                  0.6.4
datasets                                          2.18.0
debugpy                                           1.6.7
decorator                                         5.1.1
deepmerge                                         1.1.1
Deprecated                                        1.2.14
dill                                              0.3.8
dirtyjson                                         1.0.8
diskcache                                         5.6.3
distro                                            1.9.0
dulwich                                           0.22.1
einops                                            0.8.0
elastic-transport                                 8.13.0
elasticsearch                                     8.13.1
entrypoints                                       0.4
environs                                          9.5.0
et-xmlfile                                        1.1.0
exceptiongroup                                    1.2.0
executing                                         2.0.1
fastapi                                           0.110.0
fastavro                                          1.9.5
fastembed                                         0.3.1
fastrlock                                         0.8.2
filelock                                          3.13.1
FlagEmbedding                                     1.2.9
flash-attn                                        2.5.9.post1
flatbuffers                                       24.3.7
frozenlist                                        1.4.1
fs                                                2.4.16
fsspec                                            2024.2.0
ghostscript                                       0.7
gitdb                                             4.0.11
GitPython                                         3.1.42
google-auth                                       2.29.0
googleapis-common-protos                          1.63.0
greenlet                                          3.0.3
grpcio                                            1.63.0
grpcio-tools                                      1.62.2
h11                                               0.14.0
h2                                                4.1.0
hpack                                             4.0.0
html2text                                         2024.2.26
httpcore                                          1.0.4
httptools                                         0.6.1
httpx                                             0.27.0
httpx-sse                                         0.4.0
httpx-ws                                          0.6.0
huggingface-hub                                   0.23.4
humanfriendly                                     10.0
hyperframe                                        6.0.1
idna                                              3.6
imageio                                           2.34.0
importlib-metadata                                6.11.0
importlib_resources                               6.4.0
inflection                                        0.5.1
inquirerpy                                        0.3.4
interegular                                       0.3.3
ipykernel                                         6.29.3
ipython                                           8.22.2
jedi                                              0.19.1
Jinja2                                            3.1.3
jmespath                                          1.0.1
joblib                                            1.3.2
jsonpatch                                         1.33
jsonpath-ng                                       1.6.1
jsonpointer                                       3.0.0
jsonschema                                        4.21.1
jsonschema-specifications                         2023.12.1
jupyter-client                                    7.3.4
jupyter_core                                      5.7.2
kubernetes                                        29.0.0
langchain                                         0.2.7
langchain-community                               0.2.7
langchain-core                                    0.2.18
langchain-openai                                  0.1.16
langchain-text-splitters                          0.2.2
langcodes                                         3.4.0
langsmith                                         0.1.85
language_data                                     1.2.0
lark                                              1.1.9
lazy_loader                                       0.3
Levenshtein                                       0.25.0
lightning                                         2.2.1
lightning-utilities                               0.11.2
llama-index                                       0.10.37
llama-index-agent-openai                          0.1.7
llama-index-cli                                   0.1.11
llama-index-core                                  0.10.47
llama-index-embeddings-huggingface                0.1.4
llama-index-embeddings-openai                     0.1.7
llama-index-indices-managed-llama-cloud           0.1.5
llama-index-legacy                                0.9.48
llama-index-llms-huggingface                      0.2.3
llama-index-llms-huggingface-api                  0.1.0
llama-index-llms-ollama                           0.1.2
llama-index-llms-openai                           0.1.19
llama-index-llms-openai-like                      0.1.3
llama-index-llms-openllm                          0.2.0
llama-index-llms-vllm                             0.1.6
llama-index-multi-modal-llms-openai               0.1.4
llama-index-postprocessor-cohere-rerank           0.1.7
llama-index-postprocessor-flag-embedding-reranker 0.1.2
llama-index-postprocessor-jinaai-rerank           0.1.6
llama-index-postprocessor-nvidia-rerank           0.1.5
llama-index-program-openai                        0.1.4
llama-index-question-gen-openai                   0.1.3
llama-index-readers-file                          0.1.12
llama-index-readers-llama-parse                   0.1.3
llama-index-readers-nougat-ocr                    0.1.3
llama-index-readers-pdf-table                     0.1.3
llama-index-readers-smart-pdf-loader              0.1.3
llama-index-retrievers-bm25                       0.1.3
llama-index-vector-stores-chroma                  0.1.6
llama-index-vector-stores-elasticsearch           0.2.0
llama-index-vector-stores-milvus                  0.1.14
llama-index-vector-stores-qdrant                  0.2.8
llama-index-vector-stores-weaviate                1.0.2
llama-parse                                       0.3.9
llamaindex-py-client                              0.1.19
llmsherpa                                         0.1.4
llvmlite                                          0.42.0
loguru                                            0.7.2
lxml                                              5.2.2
marisa-trie                                       1.1.1
markdown-it-py                                    3.0.0
MarkupSafe                                        2.1.5
marshmallow                                       3.21.1
matplotlib-inline                                 0.1.7
mdurl                                             0.1.2
milvus-lite                                       2.4.5
mmh3                                              4.1.0
monotonic                                         1.6
mpmath                                            1.3.0
msgpack                                           1.0.8
multidict                                         6.0.5
multiprocess                                      0.70.16
munch                                             4.0.0
murmurhash                                        1.0.10
mypy-extensions                                   1.0.0
nest_asyncio                                      1.6.0
networkx                                          3.2.1
ninja                                             1.11.1.1
nltk                                              3.8.1
nougat-ocr                                        0.1.17
numba                                             0.59.1
numpy                                             1.26.4
nvidia-cublas-cu12                                12.1.3.1
nvidia-cuda-cupti-cu12                            12.1.105
nvidia-cuda-nvrtc-cu12                            12.1.105
nvidia-cuda-runtime-cu12                          12.1.105
nvidia-cudnn-cu12                                 8.9.2.26
nvidia-cufft-cu12                                 11.0.2.54
nvidia-curand-cu12                                10.3.2.106
nvidia-cusolver-cu12                              11.4.5.107
nvidia-cusparse-cu12                              12.1.0.106
nvidia-ml-py                                      11.525.150
nvidia-nccl-cu12                                  2.18.1
nvidia-nvjitlink-cu12                             12.4.99
nvidia-nvtx-cu12                                  12.1.105
oauthlib                                          3.2.2
onnx                                              1.16.0
onnxruntime                                       1.17.1
openai                                            1.35.10
opencv-python                                     4.9.0.80
opencv-python-headless                            4.9.0.80
openllm                                           0.6.7
openpyxl                                          3.1.2
opentelemetry-api                                 1.23.0
opentelemetry-exporter-otlp-proto-common          1.23.0
opentelemetry-exporter-otlp-proto-grpc            1.23.0
opentelemetry-instrumentation                     0.44b0
opentelemetry-instrumentation-aiohttp-client      0.41b0
opentelemetry-instrumentation-asgi                0.44b0
opentelemetry-instrumentation-fastapi             0.44b0
opentelemetry-proto                               1.23.0
opentelemetry-sdk                                 1.23.0
opentelemetry-semantic-conventions                0.44b0
opentelemetry-util-http                           0.44b0
orjson                                            3.9.15
outlines                                          0.0.37
overrides                                         7.7.0
packaging                                         23.2
pandas                                            2.2.1
parameterized                                     0.9.0
parso                                             0.8.4
pathlib                                           1.0.1
pathspec                                          0.12.1
pdfminer.six                                      20231228
pexpect                                           4.9.0
pfzy                                              0.3.4
pickleshare                                       0.7.5
pillow                                            10.3.0
pip                                               23.3.1
pip-requirements-parser                           32.0.1
platformdirs                                      4.2.1
ply                                               3.11
portalocker                                       2.8.2
posthog                                           3.5.0
preshed                                           3.0.9
prometheus_client                                 0.20.0
prompt-toolkit                                    3.0.42
protobuf                                          4.25.3
psutil                                            5.9.0
ptyprocess                                        0.7.0
pulsar-client                                     3.4.0
pure-eval                                         0.2.2
pyaml                                             24.7.0
pyarrow                                           15.0.2
pyarrow-hotfix                                    0.6
pyasn1                                            0.5.1
pyasn1-modules                                    0.3.0
pycparser                                         2.21
pydantic                                          2.6.4
pydantic_core                                     2.16.3
pydeck                                            0.8.1b0
Pygments                                          2.17.2
pymilvus                                          2.4.3
PyMuPDF                                           1.24.0
PyMuPDFb                                          1.24.0
pynvml                                            11.5.0
pyparsing                                         3.1.2
pypdf                                             4.1.0
pypdfium2                                         4.28.0
PyPika                                            0.48.9
pyproject_hooks                                   1.0.0
pysbd                                             0.3.4
PyStemmer                                         2.2.0.1
python-dateutil                                   2.9.0
python-dotenv                                     1.0.1
python-json-logger                                2.0.7
python-Levenshtein                                0.25.0
python-multipart                                  0.0.9
pytorch-lightning                                 2.2.1
pytz                                              2024.1
PyYAML                                            6.0.1
pyzmq                                             25.1.2
qdrant-client                                     1.9.1
questionary                                       2.0.1
ragas                                             0.1.10
rank-bm25                                         0.2.2
rapidfuzz                                         3.7.0
ray                                               2.10.0
referencing                                       0.34.0
regex                                             2023.12.25
requests                                          2.31.0
requests-oauthlib                                 2.0.0
rich                                              13.7.1
rpds-py                                           0.18.0
rsa                                               4.9
ruamel.yaml                                       0.18.6
ruamel.yaml.clib                                  0.2.8
s3transfer                                        0.10.2
safetensors                                       0.4.2
schema                                            0.7.7
scikit-image                                      0.22.0
scikit-learn                                      1.4.1.post1
scipy                                             1.12.0
sconf                                             0.2.5
sentence-transformers                             2.6.1
sentencepiece                                     0.2.0
setuptools                                        68.2.2
simple-di                                         0.1.5
six                                               1.16.0
smart-open                                        6.4.0
smmap                                             5.0.1
sniffio                                           1.3.1
snowballstemmer                                   2.2.0
soupsieve                                         2.5
spacy                                             3.7.4
spacy-legacy                                      3.0.12
spacy-loggers                                     1.0.5
SQLAlchemy                                        2.0.29
srsly                                             2.4.8
stack-data                                        0.6.2
starlette                                         0.36.3
streamlit                                         1.35.0
streamlit-chat                                    0.1.1
striprtf                                          0.0.26
sympy                                             1.12
tabulate                                          0.9.0
tenacity                                          8.2.3
text-generation                                   0.7.0
thinc                                             8.2.3
threadpoolctl                                     3.4.0
tifffile                                          2024.2.12
tiktoken                                          0.7.0
timm                                              0.5.4
tokenizers                                        0.15.2
toml                                              0.10.2
tomli                                             2.0.1
tomli_w                                           1.0.0
toolz                                             0.12.1
torch                                             2.1.2
torchmetrics                                      1.3.2
tornado                                           6.1
tqdm                                              4.66.2
traitlets                                         5.14.3
transformers                                      4.39.1
triton                                            2.1.0
typer                                             0.9.4
types-requests                                    2.32.0.20240712
typing_extensions                                 4.10.0
typing-inspect                                    0.9.0
tzdata                                            2024.1
ujson                                             5.10.0
urllib3                                           2.2.1
uv                                                0.2.33
uvicorn                                           0.29.0
uvloop                                            0.19.0
validators                                        0.33.0
vllm                                              0.3.3
wasabi                                            1.1.2
watchdog                                          4.0.0
watchfiles                                        0.21.0
wcwidth                                           0.2.13
weasel                                            0.3.4
weaviate-client                                   4.7.1
websocket-client                                  1.7.0
websockets                                        12.0
wheel                                             0.41.2
wrapt                                             1.16.0
wsproto                                           1.2.0
xformers                                          0.0.23.post1
xxhash                                            3.4.1
yarl                                              1.9.4
zipp                                              3.18.1
